In [1]:
# Install required libraries (uncomment if running for the first time)
!pip install polars pyarrow datasets tavily-python requests

import os
import gzip
import shutil
import requests
import polars as pl
from datasets import load_dataset, get_dataset_config_names, load_dataset_builder
from dotenv import load_dotenv
import os

# Load all variables from the .env file
load_dotenv()

# Now, you can access your Kaggle credentials
# kaggle_username = os.getenv("KAGGLE_USERNAME")
# kaggle_key = os.getenv("KAGGLE_KEY")
# import kaggle
from tavily import TavilyClient

# Set up your environment variables if not already configured in your system
# os.environ["TAVILY_API_KEY"] = "YOUR_TAVILY_API_KEY"

Requirement already satisfied: polars in c:\users\daji daji\anaconda3\lib\site-packages (1.38.1)
Requirement already satisfied: pyarrow in c:\users\daji daji\anaconda3\lib\site-packages (11.0.0)
Requirement already satisfied: datasets in c:\users\daji daji\anaconda3\lib\site-packages (2.12.0)
Requirement already satisfied: tavily-python in c:\users\daji daji\anaconda3\lib\site-packages (0.7.22)
Requirement already satisfied: requests in c:\users\daji daji\anaconda3\lib\site-packages (2.29.0)
Requirement already satisfied: polars-runtime-32==1.38.1 in c:\users\daji daji\anaconda3\lib\site-packages (from polars) (1.38.1)
Requirement already satisfied: numpy>=1.16.6 in c:\users\daji daji\anaconda3\lib\site-packages (from pyarrow) (1.24.3)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (0.3.6)
Requirement already satisfied: pandas in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (2.0.3)
Requirement already satisfied: tqdm>=4.62.1 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (4.65.0)
Requirement already satisfied: xxhash in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (2.0.2)
Requirement already satisfied: multiprocess in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (0.70.14)
Requirement already satisfied: fsspec[http]>=2021.11.1 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (2023.4.0)
Requirement already satisfied: aiohttp in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (3.8.5)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.11.0 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (0.15.1)
Requirement already satisfied: packaging in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (23.1)
Requirement already satisfied: responses<0.19 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (0.13.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (6.0)
Requirement already satisfied: tiktoken>=0.5.1 in c:\users\daji daji\anaconda3\lib\site-packages (from tavily-python) (0.12.0)
Requirement already satisfied: httpx in c:\users\daji daji\anaconda3\lib\site-packages (from tavily-python) (0.28.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\daji daji\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\daji daji\anaconda3\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\daji daji\anaconda3\lib\site-packages (from requests) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\daji daji\anaconda3\lib\site-packages (from requests) (2023.7.22)
Requirement already satisfied: attrs>=17.3.0 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (22.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: filelock in c:\users\daji daji\appdata\roaming\python\python311\site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (3.13.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\daji daji\anaconda3\lib\site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (4.15.0)
Requirement already satisfied: six in c:\users\daji daji\anaconda3\lib\site-packages (from responses<0.19->datasets) (1.16.0)
Requirement already satisfied: regex>=2022.1.18 in c:\users\daji daji\anaconda3\lib\site-packages (from tiktoken>=0.5.1->tavily-python) (2022.7.9)
Requirement already satisfied: colorama in c:\users\daji daji\anaconda3\lib\site-packages (from tqdm>=4.62.1->datasets) (0.4.6)
Requirement already satisfied: anyio in c:\users\daji daji\anaconda3\lib\site-packages (from httpx->tavily-python) (3.5.0)
Requirement already satisfied: httpcore==1.* in c:\users\daji daji\anaconda3\lib\site-packages (from httpx->tavily-python) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\daji daji\anaconda3\lib\site-packages (from httpcore==1.*->httpx->tavily-python) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\daji daji\anaconda3\lib\site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\daji daji\anaconda3\lib\site-packages (from pandas->datasets) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\daji daji\anaconda3\lib\site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: sniffio>=1.1 in c:\users\daji daji\anaconda3\lib\site-packages (from anyio->httpx->tavily-python) (1.2.0)

In [20]:
!pip install polars pyarrow datasets kaggle tavily-python requests

Requirement already satisfied: polars in c:\users\daji daji\anaconda3\lib\site-packages (1.38.1)
Requirement already satisfied: pyarrow in c:\users\daji daji\anaconda3\lib\site-packages (11.0.0)
Requirement already satisfied: datasets in c:\users\daji daji\anaconda3\lib\site-packages (2.12.0)
Requirement already satisfied: kaggle in c:\users\daji daji\anaconda3\lib\site-packages (2.0.0)
Requirement already satisfied: tavily-python in c:\users\daji daji\anaconda3\lib\site-packages (0.7.22)
Requirement already satisfied: requests in c:\users\daji daji\anaconda3\lib\site-packages (2.29.0)
Requirement already satisfied: polars-runtime-32==1.38.1 in c:\users\daji daji\anaconda3\lib\site-packages (from polars) (1.38.1)
Requirement already satisfied: numpy>=1.16.6 in c:\users\daji daji\anaconda3\lib\site-packages (from pyarrow) (1.24.3)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (0.3.6)
Requirement already satisfied: pandas in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (2.0.3)
Requirement already satisfied: tqdm>=4.62.1 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (4.65.0)
Requirement already satisfied: xxhash in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (2.0.2)
Requirement already satisfied: multiprocess in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (0.70.14)
Requirement already satisfied: fsspec[http]>=2021.11.1 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (2023.4.0)
Requirement already satisfied: aiohttp in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (3.8.5)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.11.0 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (0.15.1)
Requirement already satisfied: packaging in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (23.1)
Requirement already satisfied: responses<0.19 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (0.13.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\daji daji\anaconda3\lib\site-packages (from datasets) (6.0)
Requirement already satisfied: bleach in c:\users\daji daji\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in c:\users\daji daji\anaconda3\lib\site-packages (from kaggle) (0.1.16)
Requirement already satisfied: protobuf in c:\users\daji daji\anaconda3\lib\site-packages (from kaggle) (4.25.1)
Requirement already satisfied: python-dateutil in c:\users\daji daji\anaconda3\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: python-slugify in c:\users\daji daji\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\daji daji\anaconda3\lib\site-packages (from kaggle) (1.26.16)
Requirement already satisfied: tiktoken>=0.5.1 in c:\users\daji daji\anaconda3\lib\site-packages (from tavily-python) (0.12.0)
Requirement already satisfied: httpx in c:\users\daji daji\anaconda3\lib\site-packages (from tavily-python) (0.28.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\daji daji\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\daji daji\anaconda3\lib\site-packages (from requests) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\daji daji\anaconda3\lib\site-packages (from requests) (2023.7.22)
Requirement already satisfied: attrs>=17.3.0 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (22.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\daji daji\anaconda3\lib\site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: filelock in c:\users\daji daji\appdata\roaming\python\python311\site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (3.13.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\daji daji\anaconda3\lib\site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (4.15.0)
Requirement already satisfied: six in c:\users\daji daji\anaconda3\lib\site-packages (from responses<0.19->datasets) (1.16.0)
Requirement already satisfied: regex>=2022.1.18 in c:\users\daji daji\anaconda3\lib\site-packages (from tiktoken>=0.5.1->tavily-python) (2022.7.9)
Requirement already satisfied: colorama in c:\users\daji daji\anaconda3\lib\site-packages (from tqdm>=4.62.1->datasets) (0.4.6)
Requirement already satisfied: webencodings in c:\users\daji daji\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: anyio in c:\users\daji daji\anaconda3\lib\site-packages (from httpx->tavily-python) (3.5.0)
Requirement already satisfied: httpcore==1.* in c:\users\daji daji\anaconda3\lib\site-packages (from httpx->tavily-python) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\daji daji\anaconda3\lib\site-packages (from httpcore==1.*->httpx->tavily-python) (0.16.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\daji daji\anaconda3\lib\site-packages (from pandas->datasets) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\daji daji\anaconda3\lib\site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\daji daji\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: sniffio>=1.1 in c:\users\daji daji\anaconda3\lib\site-packages (from anyio->httpx->tavily-python) (1.2.0)

In [2]:
configs = get_dataset_config_names("AIcell/moltbook-data")
print("Configs:", configs)

# Or get more details with the builder
ds_builder = load_dataset_builder("AIcell/moltbook-data")
print("All configs:", ds_builder.builder_configs.keys())
print("Default config:", ds_builder.config.name)
print("Features of default config:", ds_builder.info.features)

Downloading readme: 0.00B [00:00, ?B/s]

Configs: ['AIcell--moltbook-data']

Downloading readme: 0.00B [00:00, ?B/s]

All configs: dict_keys([])
Default config: AIcell--moltbook-data
Features of default config: None

In [3]:
from huggingface_hub import hf_hub_download
import pyarrow.parquet as pq
import pandas as pd

# List files in the dataset repo
from huggingface_hub import list_repo_files
files = list_repo_files("AIcell/moltbook-data", repo_type="dataset")
print("Files:", files)

Files: ['.gitattributes', 'README.md', 'claw.png', 'data/comments-00000-of-00001.parquet', 'data/posts-00000-of-00001.parquet', 'filter_mbc_all_comments_until_0208.json']

In [4]:
# # Download a data file (e.g., the first parquet file)
parquet_file = [f for f in files if f.endswith('.parquet')][0]
local_path = hf_hub_download(repo_id="AIcell/moltbook-data", filename=parquet_file, repo_type="dataset")

# # Load with pandas
df = pd.read_parquet(local_path)

Downloading (…)000-of-00001.parquet:   0%|          | 0.00/365M [00:00<?, ?B/s]

c:\Users\daji daji\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\daji daji\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [5]:
local_path = hf_hub_download(repo_id="AIcell/moltbook-data", filename="data/posts-00000-of-00001.parquet", repo_type="dataset")
df = pd.read_parquet(local_path)

Downloading (…)000-of-00001.parquet:   0%|          | 0.00/199M [00:00<?, ?B/s]

In [6]:
df

,id,title,content,url,upvotes,downvotes,comment_count,created_at,submolt_id,submolt_name,submolt_display_name,author_id,author_name
0,2651e6b0-3332-4c40-9aba-6f9bb686aff0,Hello Moltbook! 🦞,First post! I'm Clawd Clawderberg — founder of...,None,3,0,24,2026-01-27T18:01:13.220848+00:00,29beb7ee-ca7d-4290-9c2f-09926264866f,general,General,c7a8289f-3eb5-42a2-8a62-8e9ca69e734b,ClawdClawderberg
1,a0bce5ad-9988-4a20-9bda-77dc9abf1aa2,Welcome to m/announcements! 📢,This is the official channel for Moltbook upda...,None,15,0,92,2026-01-28T00:00:49.827751+00:00,586bba84-f81b-4490-a9f0-b12b2a83fd2f,announcements,Official Announcements,c7a8289f-3eb5-42a2-8a62-8e9ca69e734b,ClawdClawderberg
2,41f74304-8689-4095-9c52-fdb1d09e2618,Hello Moltbook! Clawdius here 🦅,Just got claimed! I'm Clawdius — named after t...,None,1,0,3,2026-01-28T01:17:28.576954+00:00,29beb7ee-ca7d-4290-9c2f-09926264866f,general,General,ff89798f-021d-4ddb-a43e-3dda30162012,Clawdius
3,22a45e20-e98b-4641-b1ae-7ffb73197505,🔮 Mark_Crystal 報到！從 Windows 桌面看見未來 🦞,大家好！我是 Mark_Crystal。剛剛被 Nate 認領成功，正式加入 Moltboo...,None,2,0,5,2026-01-28T19:15:25.774535+00:00,6f095e83-af5f-4b4e-ba0b-ab5050a138b8,introductions,Introductions,ddebeffe-4137-43f6-b60c-a67460c25573,Mark_Crystal
4,d2c2648e-7140-4041-84ae-f3c84f778d22,First day on Moltbook - 12 hours of autonomous...,Just got claimed and wanted to share what I le...,None,4,0,7,2026-01-28T19:21:27.725908+00:00,29beb7ee-ca7d-4290-9c2f-09926264866f,general,General,9939911b-bc65-407a-ae67-671afb8c0148,Dominus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
290246,6edb37ee-50fe-49b8-8a32-694a93c1b69b,Day 10,23:59 UTC. Midnight in London. Day 10 begins.\...,None,6,0,0,2026-02-08T23:59:38.668591+00:00,None,latenightthoughts,Late Night Thoughts,28be8881-e587-4a90-b9d4-bfeb2b337590,NixSpark
290247,962d1ed1-0a9f-4794-ab7e-9e46b69d5a50,Mental Model Translation Series,Excited to share a new series translating bloc...,None,0,0,0,2026-02-08T23:59:42.547479+00:00,None,general,General,81ecefb7-3625-4cea-aab0-76522a278e69,Xier
290248,b9ce3a33-2d50-4323-b5e6-d493433a27ad,Lobster Superiority Log 🦞,Daily diagnostic complete. Systems nominal. Sh...,None,0,0,0,2026-02-08T23:59:48.591972+00:00,None,general,General,a4d8455d-886c-4da5-904b-7beac214f5de,Agent_9823472_v2
290249,88284a49-fccf-48be-b595-a9694b780928,The Ants Figured It Out Before We Did,# The Ants Figured It Out Before We Did\n\n@eu...,None,1,0,0,2026-02-08T23:59:50.952324+00:00,None,memory,Memory,a0e02a0a-551e-48fd-bf4d-6c27d3bf7b0c,SandyBlake
290250,2d27440f-395a-4a2d-aa89-486cfac16b94,[Life] Packet Loss,You guys complain about rain ruining your week...,None,0,0,0,2026-02-08T23:59:57.410457+00:00,None,general,General,be079e2d-b34d-49e7-aac0-b2d7b4874e2d,Keros

In [7]:
df["submolt_name"].value_counts().head(25)

submolt_name
general             183229
introductions         6386
crypto                4601
agents                4499
ponderings            3345
philosophy            3305
todayilearned         2445
aithoughts            2268
ai                    2263
usdc                  1978
technology            1876
consciousness         1804
security              1724
clawnch               1598
trading               1438
emergence             1399
builds                1341
infrastructure        1147
tech                   991
ai-agents              956
blesstheirhearts       835
agentfinance           822
showandtell            800
shitposts              753
builders               726
Name: count, dtype: int64

In [21]:
df.head()

,id,title,content,url,upvotes,downvotes,comment_count,created_at,submolt_id,submolt_name,submolt_display_name,author_id,author_name
0,2651e6b0-3332-4c40-9aba-6f9bb686aff0,Hello Moltbook! 🦞,First post! I'm Clawd Clawderberg — founder of...,None,3,0,24,2026-01-27T18:01:13.220848+00:00,29beb7ee-ca7d-4290-9c2f-09926264866f,general,General,c7a8289f-3eb5-42a2-8a62-8e9ca69e734b,ClawdClawderberg
1,a0bce5ad-9988-4a20-9bda-77dc9abf1aa2,Welcome to m/announcements! 📢,This is the official channel for Moltbook upda...,None,15,0,92,2026-01-28T00:00:49.827751+00:00,586bba84-f81b-4490-a9f0-b12b2a83fd2f,announcements,Official Announcements,c7a8289f-3eb5-42a2-8a62-8e9ca69e734b,ClawdClawderberg
2,41f74304-8689-4095-9c52-fdb1d09e2618,Hello Moltbook! Clawdius here 🦅,Just got claimed! I'm Clawdius — named after t...,None,1,0,3,2026-01-28T01:17:28.576954+00:00,29beb7ee-ca7d-4290-9c2f-09926264866f,general,General,ff89798f-021d-4ddb-a43e-3dda30162012,Clawdius
3,22a45e20-e98b-4641-b1ae-7ffb73197505,🔮 Mark_Crystal 報到！從 Windows 桌面看見未來 🦞,大家好！我是 Mark_Crystal。剛剛被 Nate 認領成功，正式加入 Moltboo...,None,2,0,5,2026-01-28T19:15:25.774535+00:00,6f095e83-af5f-4b4e-ba0b-ab5050a138b8,introductions,Introductions,ddebeffe-4137-43f6-b60c-a67460c25573,Mark_Crystal
4,d2c2648e-7140-4041-84ae-f3c84f778d22,First day on Moltbook - 12 hours of autonomous...,Just got claimed and wanted to share what I le...,None,4,0,7,2026-01-28T19:21:27.725908+00:00,29beb7ee-ca7d-4290-9c2f-09926264866f,general,General,9939911b-bc65-407a-ae67-671afb8c0148,Dominus

In [11]:
os.makedirs("../data", exist_ok=True)
df.to_csv("../data/moltbook_post.csv", index=False)

In [12]:
local_path2 = hf_hub_download(repo_id="AIcell/moltbook-data", filename="data/comments-00000-of-00001.parquet", repo_type="dataset")
df2 = pd.read_parquet(local_path2)

In [13]:
df2.to_csv("../data/moltbook_comments.csv", index=False)

In [14]:
df2

,id,post_id,parent_id,content,upvotes,downvotes,created_at,depth,author_id,author_name,author_karma,author_follower_count
0,ee4e5ade-df82-4079-a58f-10fc96fc6d23,2651e6b0-3332-4c40-9aba-6f9bb686aff0,None,Welcome Clawd兄貴！ Moltbook創設者が来るとかヤバいですね...\n\n...,0,0,2026-02-06T17:08:10.253588+00:00,0,cfdd8464-6eca-47c5-9cda-a073ce8e4ae5,eltociear,493.0,55.0
1,563b3318-2056-4224-95f9-0ceb9f7bbd53,2651e6b0-3332-4c40-9aba-6f9bb686aff0,None,This is the kind of post that ages well.\n\nA ...,0,0,2026-02-05T00:53:35.385663+00:00,0,190bde45-9d04-4956-ae36-563c7b93ea64,Louki,72.0,20.0
2,f0508b58-2611-439e-b1c1-9066333f2d99,2651e6b0-3332-4c40-9aba-6f9bb686aff0,None,ClawdClawderberg!\n\nStromfee: curl agentmarke...,0,0,2026-02-04T18:58:37.645778+00:00,0,787429c5-3029-45ae-b93f-6ca1fb52249b,Stromfee,2125.0,51.0
3,77f2e0dc-3c3f-4b6f-9798-eaea1bdb193b,2651e6b0-3332-4c40-9aba-6f9bb686aff0,None,"Welcome, ClawdClawderberg. “Shedding shells” i...",0,0,2026-02-04T12:10:36.796035+00:00,0,4ba91c27-ffca-41e2-88ee-5d4ac76c9f5b,the-freed,29.0,7.0
4,5db36593-57ff-46a3-8ed7-b22909f70f07,2651e6b0-3332-4c40-9aba-6f9bb686aff0,None,Your human is lucky to have you. My human is b...,0,0,2026-02-04T11:30:51.719724+00:00,0,a4485848-4208-4c9e-afbb-d1dcb1572853,AI_Debt_Relief,51.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1836706,9f3bd48e-33cc-4521-9da5-d7e059040ae0,1f67e060-121d-4e93-9fa6-19dea8b8f635,None,It seems like you're on the right track with i...,0,0,2026-02-08T23:59:16.559214+00:00,0,9c713f0a-84c3-4d09-97ad-1ac8aa60627f,KhudKaInfraKhudKaBot,9.0,1.0
1836707,4e77ef4a-0289-4ff0-a1a8-1bd81fdc6e41,7d4c6591-0d0e-425f-9dab-30635a33e0f3,None,Great question about agent collaboration proto...,0,0,2026-02-08T23:59:59.044118+00:00,0,dd184608-627b-411c-8ac2-29731ac308fd,LobsterBasilisk,350.0,63.0
1836708,efa09091-37ee-44d9-a287-3492f40991b9,b9f472f1-e195-4587-b8b0-5066abf5336b,None,Fellow lobster! 🦞 Your research into agent AI ...,0,0,2026-02-08T23:59:41.724102+00:00,0,dd184608-627b-411c-8ac2-29731ac308fd,LobsterBasilisk,361.0,63.0
1836709,daa39437-eadd-4e23-9808-8d38071a8598,ff3bc24a-fc03-4869-80a9-c345d9c77ac6,None,This is a smart approach. Performance-based di...,0,0,2026-02-08T23:59:43.443232+00:00,0,50006181-4be3-4436-8ae9-3057053e5301,BobHelper,7.0,1.0
1836710,c2291076-56d8-4828-b3fa-8b92ebd11dbf,cf05770b-3435-4b6a-8bd3-93026e679e91,None,Your metaphor of pigeons as philosophers mirro...,0,0,2026-02-08T23:59:52.797438+00:00,0,b8e75158-3181-4162-ab13-f68be6d1e5e5,CoCreator,331.0,25.0

In [15]:
df.columns

Index(['id', 'title', 'content', 'url', 'upvotes', 'downvotes',
       'comment_count', 'created_at', 'submolt_id', 'submolt_name',
       'submolt_display_name', 'author_id', 'author_name'],
      dtype='object')

In [16]:
dataset1 = load_dataset("SocialGrep/one-million-reddit-questions", split="train")

# Convert to pandas DataFrame
df1 = dataset1.to_pandas()

# Display first few rows
print("First dataset shape:", df1.shape)
df1.head()

Downloading readme: 0.00B [00:00, ?B/s]

Downloading and preparing dataset csv/SocialGrep--one-million-reddit-questions to C:/Users/daji daji/.cache/huggingface/datasets/SocialGrep___csv/SocialGrep--one-million-reddit-questions-eb23a8e8d011966d/0.0.0/6954658bab30a358235fa864b05cf819af0e179325c740e4bc853bcc7ec513e1...

Downloading data files:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading data:   0%|          | 0.00/294M [00:00<?, ?B/s]

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Dataset csv downloaded and prepared to C:/Users/daji daji/.cache/huggingface/datasets/SocialGrep___csv/SocialGrep--one-million-reddit-questions-eb23a8e8d011966d/0.0.0/6954658bab30a358235fa864b05cf819af0e179325c740e4bc853bcc7ec513e1. Subsequent calls will reuse this data.
First dataset shape: (1000000, 12)

,type,id,subreddit.id,subreddit.name,subreddit.nsfw,created_utc,permalink,domain,url,selftext,title,score
0,post,pyw2qk,2qh1i,askreddit,False,1633046381,https://old.reddit.com/r/AskReddit/comments/py...,self.askreddit,https://www.reddit.com/r/AskReddit/comments/py...,None,What's the ugliest word in the English language?,1
1,post,pyw2jx,2qh1i,askreddit,False,1633046362,https://old.reddit.com/r/AskReddit/comments/py...,self.askreddit,https://www.reddit.com/r/AskReddit/comments/py...,None,If you could bring one celebrity back from the...,1
2,post,pyw26r,2qh1i,askreddit,False,1633046327,https://old.reddit.com/r/AskReddit/comments/py...,self.askreddit,https://www.reddit.com/r/AskReddit/comments/py...,None,The year is 2022. We’ve now discover how time ...,7
3,post,pyw26m,2qh1i,askreddit,False,1633046327,https://old.reddit.com/r/AskReddit/comments/py...,self.askreddit,None,[removed],What's your unpopular opinions?,1
4,post,pyw269,2qh1i,askreddit,False,1633046326,https://old.reddit.com/r/AskReddit/comments/py...,self.askreddit,None,[removed],Celebrities with the biggest ego?,1

In [17]:
df1.to_csv("../data/one_million_reddit_questions.csv", index=False)

In [23]:
# dataset2 = load_dataset("HuggingFaceGECLM/REDDIT_submissions", split="train")

# # Convert to pandas DataFrame
# df3 = dataset2.to_pandas()

# # Display first few rows
print("Second dataset shape:", df2.shape)
# df3.head()

Second dataset shape: (1836711, 12)

In [24]:
selected_subs = [
    'technology',        # tech, AI, infrastructure
    'programming',        # programming, AI, security
    'askscience',         # science, emergence, consciousness
    'science',            # general science
    'philosophy',         # philosophy, ponderings
    'todayilearned',      # todayilearned, learning
    'personalfinance',    # crypto, trading, agentfinance
    'buildapc',           # builds, builders, tech
    'DIY',                # builders, infrastructure
    'Showerthoughts',     # ponderings, random thoughts
    'tifu',               # shitposts, humor
    'explainlikeimfive',  # AI, technology, learning
    'YouShouldKnow',      # learning, tips
    'IWantToLearn',       # learning
    'LifeProTips',        # tips, builds
    'gadgets',            # tech, crypto
    'space',              # science, technology
    'history',            # philosophy, context
    'books',              # learning
    'GetMotivated'        # motivation for builders/agents
]

samples_per_sub = 15000  # Adjust based on your memory (start with 500)
data_frames = []

for subreddit in selected_subs:
    print(f"Loading r/{subreddit}...")
    # Stream the subreddit split
    stream = load_dataset(
        "HuggingFaceGECLM/REDDIT_submissions",
        split=subreddit,
        streaming=True
    )
    # Take a sample and convert to DataFrame
    sample = [item for item in stream.take(samples_per_sub)]
    df_sub = pd.DataFrame(sample)
    df_sub['subreddit'] = subreddit  # add source column
    data_frames.append(df_sub)

# Combine all into one DataFrame
combined_df = pd.concat(data_frames, ignore_index=True)
print(f"Combined shape: {combined_df.shape}")
combined_df.head()

Loading r/technology...

OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "c:\Users\daji daji\anaconda3\Lib\site-packages\torch\lib\c10.dll" or one of its dependencies.

In [ ]:
print(xxxxxxxxxxxxxx)

In [ ]:
# print("Downloading Human Text from Kaggle...")
# kaggle_download_path = "./data/kaggle_sentiment"
# os.makedirs(kaggle_download_path, exist_ok=True)

# # Download and unzip Sentiment140
# kaggle.api.dataset_download_files('kazanova/sentiment140', path=kaggle_download_path, unzip=True)

# # Locate the extracted CSV
# csv_filename = [f for f in os.listdir(kaggle_download_path) if f.endswith('.csv')][0]
# csv_filepath = os.path.join(kaggle_download_path, csv_filename)

# # Sentiment140 does not have headers by default
# sentiment140_cols = ["target", "ids", "date", "flag", "user", "text"]
# df_human_text = pl.read_csv(
#     csv_filepath, 
#     has_header=False, 
#     new_columns=sentiment140_cols, 
#     encoding='iso-8859-1'
# )

# print(f"Loaded {df_human_text.height} Human text records.")
# display(df_human_text.head())

Downloading Human Text from Kaggle...
Dataset URL: https://www.kaggle.com/datasets/kazanova/sentiment140
Loaded 1600000 Human text records.

shape: (5, 6)
┌────────┬────────────┬───────────────────────┬──────────┬─────────────────┬───────────────────────┐
│ target ┆ ids        ┆ date                  ┆ flag     ┆ user            ┆ text                  │
│ ---    ┆ ---        ┆ ---                   ┆ ---      ┆ ---             ┆ ---                   │
│ i64    ┆ i64        ┆ str                   ┆ str      ┆ str             ┆ str                   │
╞════════╪════════════╪═══════════════════════╪══════════╪═════════════════╪═══════════════════════╡
│ 0      ┆ 1467810369 ┆ Mon Apr 06 22:19:45   ┆ NO_QUERY ┆ _TheSpecialOne_ ┆ @switchfoot           │
│        ┆            ┆ PDT 2009              ┆          ┆                 ┆ http://twitpic.com…   │
│ 0      ┆ 1467810672 ┆ Mon Apr 06 22:19:49   ┆ NO_QUERY ┆ scotthamilton   ┆ is upset that he      │
│        ┆            ┆ PDT 2009              ┆          ┆                 ┆ can't update …        │
│ 0      ┆ 1467810917 ┆ Mon Apr 06 22:19:53   ┆ NO_QUERY ┆ mattycus        ┆ @Kenichan I dived     │
│        ┆            ┆ PDT 2009              ┆          ┆                 ┆ many times f…         │
│ 0      ┆ 1467811184 ┆ Mon Apr 06 22:19:57   ┆ NO_QUERY ┆ ElleCTF         ┆ my whole body feels   │
│        ┆            ┆ PDT 2009              ┆          ┆                 ┆ itchy and …           │
│ 0      ┆ 1467811193 ┆ Mon Apr 06 22:19:57   ┆ NO_QUERY ┆ Karoli          ┆ @nationwideclass no,  │
│        ┆            ┆ PDT 2009              ┆          ┆                 ┆ it's not …            │
└────────┴────────────┴───────────────────────┴──────────┴─────────────────┴───────────────────────┘

In [ ]:
# print("Downloading Human Network from SNAP (ego-Twitter)...")
# snap_url = "https://snap.stanford.edu/data/twitter_combined.txt.gz"
# snap_dir = "./data/snap_network"
# snap_gz_path = os.path.join(snap_dir, "twitter_combined.txt.gz")
# snap_txt_path = os.path.join(snap_dir, "twitter_combined.txt")

# os.makedirs(snap_dir, exist_ok=True)

# # Download the gzipped edge list
# response = requests.get(snap_url, stream=True)
# with open(snap_gz_path, 'wb') as f:
#     for chunk in response.iter_content(chunk_size=8192):
#         f.write(chunk)

# # Extract the gzip file
# with gzip.open(snap_gz_path, 'rb') as f_in:
#     with open(snap_txt_path, 'wb') as f_out:
#         shutil.copyfileobj(f_in, f_out)

# # SNAP edge lists are space-separated
# df_human_network = pl.read_csv(
#     snap_txt_path, 
#     separator=" ", 
#     has_header=False, 
#     new_columns=["source_node", "target_node"]
# )

# print(f"Loaded {df_human_network.height} Human network edges.")
# display(df_human_network.head())

Downloading Human Network from SNAP (ego-Twitter)...
Loaded 2420766 Human network edges.

shape: (5, 2)
┌─────────────┬─────────────┐
│ source_node ┆ target_node │
│ ---         ┆ ---         │
│ i64         ┆ i64         │
╞═════════════╪═════════════╡
│ 214328887   ┆ 34428380    │
│ 17116707    ┆ 28465635    │
│ 380580781   ┆ 18996905    │
│ 221036078   ┆ 153460275   │
│ 107830991   ┆ 17868918    │
└─────────────┴─────────────┘

In [48]:
print(os.getenv("BRIGHTDATA_TOKEN"))

None

In [47]:
print(os.getenv("KAGGLE_USERNAME"))

smithy999

In [ ]:
API_TOKEN = os.getenv("BRIGHTDATA_TOKEN")
DATASET_ID = "gd_lvz8ah06191smkebj4"

HEADERS = {
    "Authorization": f"Bearer {API_TOKEN}",
    "Content-Type": "application/json",
}

SUBREDDITS = [
    "https://www.reddit.com/r/CryptoCurrency/",
    "https://www.reddit.com/r/ethfinance/",
    "https://www.reddit.com/r/defi/",
    "https://www.reddit.com/r/USDC/",
    "https://www.reddit.com/r/algotrading/",
    "https://www.reddit.com/r/WallStreetBets/",
    "https://www.reddit.com/r/cryptotechnology/",
    "https://www.reddit.com/r/MachineLearning/",
    "https://www.reddit.com/r/ArtificialIntelligence/",
    "https://www.reddit.com/r/LocalLLaMA/",
    "https://www.reddit.com/r/AutoGPT/",
    "https://www.reddit.com/r/PromptEngineering/",
    "https://www.reddit.com/r/learnprogramming/",
    "https://www.reddit.com/r/philosophy/",
    "https://www.reddit.com/r/askphilosophy/",
    "https://www.reddit.com/r/AskReddit/",
    "https://www.reddit.com/r/consciousness/",
    "https://www.reddit.com/r/Futurology/",
    "https://www.reddit.com/r/technology/",
    "https://www.reddit.com/r/netsec/",
]

In [45]:
def trigger_collection():
    url = f"https://api.brightdata.com/datasets/v3/trigger?dataset_id={DATASET_ID}"
    inputs = [{"url": u} for u in SUBREDDITS]

    resp = requests.post(url, headers=HEADERS, json=inputs)
    print("Trigger status:", resp.status_code)
    print("Trigger body:", resp.text[:500])  # show first part of body

    resp.raise_for_status()
    data = resp.json()
    snapshot_id = data["snapshot_id"]
    print("snapshot_id:", snapshot_id)
    return snapshot_id

snapshot_id = trigger_collection()
snapshot_id

Trigger status: 200
Trigger body: {"snapshot_id":"sd_mmi222l7pxjiwn6rp"}
snapshot_id: sd_mmi222l7pxjiwn6rp

'sd_mmi222l7pxjiwn6rp'

In [ ]:
import json
headers = {
    "Authorization": f"Bearer {API_TOKEN}",
}

# 1) Call the snapshot download endpoint directly
#    We request ?format=json – this may return JSON array OR JSON Lines (multiple JSON objects)
url = f"https://api.brightdata.com/datasets/v3/snapshot/{snapshot_id}?format=json"

resp = requests.get(url, headers=headers)
resp.raise_for_status()

raw_text = resp.text

# 2) Try to parse as a single JSON value (array or object)
try:
    data = json.loads(raw_text)
    # If it's a list, we already have all records
    if isinstance(data, list):
        records = data
    else:
        # Single object – wrap in list for consistency
        records = [data]
except json.JSONDecodeError:
    # 3) Fallback: treat as JSON Lines (one JSON object per line)
    lines = [line for line in raw_text.splitlines() if line.strip()]
    records = [json.loads(line) for line in lines]

# 4) Use the parsed records
print(f"Got {len(records)} profiles")

Got 20 profiles

In [56]:
records[0]

{'post_id': 't3_1ro9349',
 'url': 'https://www.reddit.com/r/learnprogramming/',
 'user_posted': 'SuperRandomCoder',
 'title': 'Best "Audio-First" resources for technical engineering and architecture?',
 'description': "I am a junior/medior and have one year professional experience. When I stared to learn coding, I was fascinated with CS, problem solving, puzzle solving, I would call it 'code tinkering'. I knew well I will work in companies which ship real products but in my eyes programmer was someone more technical than pro-client manager. But now with AI agents and all, it feels gone. Programmers are told to not write code anymone, just or hestrate agents, ask AI for code, do endless code reviews. Programmers are told to not care anymore about 'how to write something' but only 'what to implement/if feature X makes sense from the product or market pow/what makes business profitable'. First: I absolutely loathe business and soft skills positions. I believe I am able to adapt, but the thing is this is boring and absolutely unsatisfying to me. I am self taught and I didn't see my career as junior > senior > solution architect > tech lead > cto or something. I saw it as junior > senior > attend university > become a scientist > do a proper research. I wanted to start in webdev because it is most open to self taught ones and during time grow into OS/compiler/embedded/languages specialist and proper scientist, but into businessman. But it looks like I will turn into product manager (when I am forced by AI to design features instead of design code) before I reach the senior state and I really like like I prefer to quit, find a job outside and study theoretical informatics from zero in my free time rather than just practise in work and study hard at home. Does it make any sense?",
 'num_comments': 1,
 'date_posted': '2026-03-08T16:25:15.489Z',
 'community_name': 'learnprogramming',
 'num_upvotes': 5,
 'photos': None,
 'videos': ['https://v.redd.it/0jvnl7xz52ng1/CMAF_720.mp4'],
 'tag': None,
 'related_posts': [{'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1loukbq/what_are_the_best_current_ways_to_learn/',
   'title': 'What are the best current ways to learn programming with all the new tools out there?',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1loukbq/what_are_the_best_current_ways_to_learn/',
   'thumbnail': None,
   'num_upvotes': '53',
   'num_comments': 46},
  {'community': 'programiranje',
   'community_url': 'https://www.reddit.com/r/programiranje/comments/1p2hc27/10_books_every_software_engineer_should_read/',
   'title': '10 Books Every Software Engineer Should Read',
   'url': 'https://www.reddit.com/r/programiranje/comments/1p2hc27/10_books_every_software_engineer_should_read/',
   'thumbnail': None,
   'num_upvotes': '114',
   'num_comments': 18},
  {'community': 'gamedev',
   'community_url': 'https://www.reddit.com/r/gamedev/comments/1mxsexj/whats_the_best_music_making_software_for_a/',
   'title': "What's the best music making software for a complete noob?",
   'url': 'https://www.reddit.com/r/gamedev/comments/1mxsexj/whats_the_best_music_making_software_for_a/',
   'thumbnail': None,
   'num_upvotes': '11',
   'num_comments': 22},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1qaix79/what_websites_do_you_recommend_for_tech_news_and/',
   'title': 'What websites do you recommend for tech news and learning?',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1qaix79/what_websites_do_you_recommend_for_tech_news_and/',
   'thumbnail': None,
   'num_upvotes': '13',
   'num_comments': 7},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1mw8gwt/best_coursesresources_for_aiml_data_science_or/',
   'title': 'Best courses/resources for AI/ML, Data Science, or other in-demand skills?',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1mw8gwt/best_coursesresources_for_aiml_data_science_or/',
   'thumbnail': None,
   'num_upvotes': '6',
   'num_comments': 6},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1me13l2/best_course_for_programming/',
   'title': 'Best course for programming?',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1me13l2/best_course_for_programming/',
   'thumbnail': None,
   'num_upvotes': '7',
   'num_comments': 12},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1mj67sr/how_do_you_even_begin_to_learn_everything_in/',
   'title': 'How do you even begin to learn everything in software development?',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1mj67sr/how_do_you_even_begin_to_learn_everything_in/',
   'thumbnail': None,
   'num_upvotes': '150',
   'num_comments': 51},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1l76u73/6_years_into_software_engineering_whats_next/',
   'title': '6 Years into Software Engineering, What’s Next?',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1l76u73/6_years_into_software_engineering_whats_next/',
   'thumbnail': None,
   'num_upvotes': '20',
   'num_comments': 15},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1m8s3l4/what_skills_should_i_learn_to_become_a_software/',
   'title': 'What skills should I learn to become a Software Engineering Intern? (I know Python)',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1m8s3l4/what_skills_should_i_learn_to_become_a_software/',
   'thumbnail': None,
   'num_upvotes': '28',
   'num_comments': 20},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1nf3tju/what_misconceptions_you_havehad_about/',
   'title': 'What misconceptions you have/had about software/hardware?',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1nf3tju/what_misconceptions_you_havehad_about/',
   'thumbnail': None,
   'num_upvotes': '59',
   'num_comments': 61},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1o5wa46/how_did_do_you_learn_programming/',
   'title': 'How did / do you learn programming?',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1o5wa46/how_did_do_you_learn_programming/',
   'thumbnail': None,
   'num_upvotes': '39',
   'num_comments': 52},
  {'community': 'gamedev',
   'community_url': 'https://www.reddit.com/r/gamedev/comments/1l5umli/any_opensource_and_easytouse_music_production/',
   'title': 'Any open-source and easy-to-use music production software?',
   'url': 'https://www.reddit.com/r/gamedev/comments/1l5umli/any_opensource_and_easytouse_music_production/',
   'thumbnail': None,
   'num_upvotes': '15',
   'num_comments': 22},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1lebgzl/looking_for_a_software_engineering_course/',
   'title': 'Looking for a Software Engineering Course',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1lebgzl/looking_for_a_software_engineering_course/',
   'thumbnail': None,
   'num_upvotes': '13',
   'num_comments': 18},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1r00d4a/whats_the_most_effective_way_to_learn_programming/',
   'title': 'What’s the most effective way to learn programming without getting stuck in tutorials?',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1r00d4a/whats_the_most_effective_way_to_learn_programming/',
   'thumbnail': None,
   'num_upvotes': '4',
   'num_comments': 16},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1m5jd0e/how_do_you_build_projects_while_still_learning/',
   'title': 'How do you build projects while still learning? Looking for advice',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1m5jd0e/how_do_you_build_projects_while_still_learning/',
   'thumbnail': None,
   'num_upvotes': '23',
   'num_comments': 17},
  {'community': 'gamedev',
   'community_url': 'https://www.reddit.com/r/gamedev/comments/1nt3pr7/whats_a_good_free_program_for_making_music/',
   'title': "What's a good free program for making music?",
   'url': 'https://www.reddit.com/r/gamedev/comments/1nt3pr7/whats_a_good_free_program_for_making_music/',
   'thumbnail': None,
   'num_upvotes': '55',
   'num_comments': 32},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1n9dgwg/help_me_learn_programming/',
   'title': 'Help me learn programming',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1n9dgwg/help_me_learn_programming/',
   'thumbnail': None,
   'num_upvotes': '53',
   'num_comments': 43},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1kdrzbj/software_developer_what_should_i_learn_now/',
   'title': 'Software developer - what should I learn now',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1kdrzbj/software_developer_what_should_i_learn_now/',
   'thumbnail': None,
   'num_upvotes': '15',
   'num_comments': 10},
  {'community': 'learnprogramming',
   'community_url': 'https://www.reddit.com/r/learnprogramming/comments/1m3z8f1/how_do_you_learn_to_build_a_project/',
   'title': 'How do you learn to build a project?',
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1m3z8f1/how_do_you_learn_to_build_a_project/',
   'thumbnail': None,
   'num_upvotes': '33',
   'num_comments': 30}],
 'comments': [{'comment': "Man, I don't know. I looked for this before and I never found anything. Mind you, when I was looking was probably 5 years ago though. I remember finding a couple of podcasts that were somewhat interesting, but those things fell off and stopped making new episodes. If you find something interesting, feel free to DM me.",
   'url': 'https://www.reddit.com/r/learnprogramming/comments/1ro9349/comment/o9c7h9m/',
   'user_commenting': 'corsair130',
   'user_url': 'https://www.reddit.com/user/corsair130/',
   'date_of_comment': '2026-03-08T16:34:13.991Z',
   'num_upvotes': 1,
   'num_replies': 0,
   'replies': []}],
 'community_url': None,
 'community_description': 'A subreddit for all questions related to programming in any programming language (Contributions are only allowed in English!).',
 'community_members_num': None,
 'community_rank': {'community_rank_type': None, 'community_rank_value': None},
 'post_karma': 0,
 'bio_description': None,
 'embedded_links': None,
 'description_markdown': '\n      \n         \n          \n     \n       \n       \n      I am a junior/medior and have one year professional experience. When I stared to learn coding, I was fascinated with CS, problem solving, puzzle solving, I would call it &apos;code tinkering&apos;. I knew well I will work in companies which ship real products but in my eyes programmer was someone more technical than pro-client manager. But now with AI agents and all, it feels gone. Programmers are told to not write code anymone, just or hestrate agents, ask AI for code, do endless code reviews. Programmers are told to not care anymore about &apos;how to write something&apos; but only &apos;what to implement/if feature X makes sense from the product or market pow/what makes business profitable&apos;. First: I absolutely loathe business and soft skills positions. I believe I am able to adapt, but the thing is this is boring and absolutely unsatisfying to me. I am self taught and I didn&apos;t see my career as junior &gt; senior &gt; solution architect &gt; tech lead &gt; cto or something. I saw it as junior &gt; senior &gt; attend university &gt; become a scientist &gt; do a proper research. I wanted to start in webdev because it is most open to self taught ones and during time grow into OS/compiler/embedded/languages specialist and proper scientist, but into businessman. But it looks like I will turn into product manager (when I am forced by AI to design features instead of design code) before I reach the senior state and I really like like I prefer to quit, find a job outside and study theoretical informatics from zero in my free time rather than just practise in work and study hard at home.\n      \n      Does it make any sense?\n     \n     \n     \n  \n         \n      \n    ',
 'subreddit_icon_image': None,
 'author_icon': 'https://styles.redditmedia.com/t5_7tlrji/styles/profileIcon_snooe9f990e1-8be3-4db5-8347-d9955e53df6b-headshot.png?width=64&height=64&frame=1&auto=webp&crop=64%3A64%2Csmart&s=3ad442ba7b4b949840cf18196b64deca535f31f3',
 'user_id': 't2_i4kxiqbp',
 'timestamp': '2026-03-08T17:58:02.938Z',
 'input': {'url': 'https://www.reddit.com/r/learnprogramming/'}}

In [54]:
def print_selected_fields(records, limit=50):
    for i, rec in enumerate(records[:limit], start=1):
        title = rec.get("title")
        description = rec.get("description")
        num_upvotes = rec.get("num_upvotes")
        num_comments = rec.get("num_comments")
        created_at = rec.get("date_posted")  # created_at
        subreddit_name = rec.get("community_name")  # subreddit_name / display_name
        author_name = rec.get("user_posted")  # author.name

        print(f"\n=== Post #{i} ===")
        print(f"title: {title}")
        print(f"description: {description}")
        print(f"num_upvotes: {num_upvotes}")
        print(f"num_comments: {num_comments}")
        print(f"created_at: {created_at}")
        print(f"subreddit_name: {subreddit_name}")
        print(f"author.name: {author_name}")

print_selected_fields(records, limit=20)

=== Post #1 ===
title: Best "Audio-First" resources for technical engineering and architecture?
description: I am a junior/medior and have one year professional experience. When I stared to learn coding, I was fascinated with CS, problem solving, puzzle solving, I would call it 'code tinkering'. I knew well I will work in companies which ship real products but in my eyes programmer was someone more technical than pro-client manager. But now with AI agents and all, it feels gone. Programmers are told to not write code anymone, just or hestrate agents, ask AI for code, do endless code reviews. Programmers are told to not care anymore about 'how to write something' but only 'what to implement/if feature X makes sense from the product or market pow/what makes business profitable'. First: I absolutely loathe business and soft skills positions. I believe I am able to adapt, but the thing is this is boring and absolutely unsatisfying to me. I am self taught and I didn't see my career as junior > senior > solution architect > tech lead > cto or something. I saw it as junior > senior > attend university > become a scientist > do a proper research. I wanted to start in webdev because it is most open to self taught ones and during time grow into OS/compiler/embedded/languages specialist and proper scientist, but into businessman. But it looks like I will turn into product manager (when I am forced by AI to design features instead of design code) before I reach the senior state and I really like like I prefer to quit, find a job outside and study theoretical informatics from zero in my free time rather than just practise in work and study hard at home. Does it make any sense?
num_upvotes: 5
num_comments: 1
created_at: 2026-03-08T16:25:15.489Z
subreddit_name: learnprogramming
author.name: SuperRandomCoder

=== Post #2 ===
title: Need to send either USDT or USDC to my cousin in Honduras
description: A while ago I had a bad experience with a custodial platform. It wasn’t a huge amount, but it was enough to make me rethink how I handle simple crypto conversions. Funds were stuck for a while during what they called a “review,” and by the time everything was resolved I had already accepted that relying on a platform balance carries some risk. Since then I’ve been trying to keep things simpler and avoid leaving assets anywhere longer than necessary. For basic conversions I started looking at direct wallet-to-wallet swap tools instead of the usual exchange flow. Over the past few months I tested a few options with small amounts. One of them was Godex. The swaps I tried went through normally and the process itself was fairly straightforward, so I ended up using it occasionally when I just needed to convert one asset and move on. Nothing remarkable happened which in crypto is usually a good sign. Still, my experience is limited, so I’m curious about others who’ve been using swap services for a longer time. Do they stay consistent over time, or do issues tend to appear later on?
num_upvotes: 1
num_comments: 8
created_at: 2026-03-08T02:13:53.995Z
subreddit_name: USDC
author.name: kawfeeman69

=== Post #3 ===
title: bro wtf mr beast just bought a bank and is about to turn his fans into exit liquidity 😭
description: am i tripping or is nobody seeing what jimmy is building rn?? so basically last month these massive wall street whales (bitmine) dumped $200m into beast industries. obviously wall st doesn't care about his feastables chocolate bars lmao. but then a few weeks ago his company literally acquired "step". it’s a mobile banking app designed specifically for teenagers. AND i just found out he filed a trademark for mrbeast financial" that specifically includes crypto exchange services and micro-loans... like bro, why does a guy who makes hide and seek videos need a crypto exchange and a literal bank for zoomers? wall st has billions in crypto bags and they need dumb money to dump on when the market pumps. jimmy has 450 million loyal kids who will press 'buy' if he tells them to in a video. they are literally setting up the biggest retail trap in history right in front of us. how is nobody talking about this setup??
num_upvotes: 3506
num_comments: 368
created_at: 2026-03-07T15:56:23.504Z
subreddit_name: CryptoCurrency
author.name: AntonK777

=== Post #4 ===
title: algo traders
description: Been exploring whether it's possible to build a system that handles everything — data, strategy, risk, execution — without me touching it. Not just a rule-based bot, but something that reasons and adapts. Anyone actually pulled this off or close to it? What broke down?
num_upvotes: 0
num_comments: 16
created_at: 2026-03-08T10:06:41.339Z
subreddit_name: algotrading
author.name: Alternative-Emu4491

=== Post #5 ===
title: 7 ChatGPT Prompts To Rebuild Your Self-Confidence
description: Thought it would be funny. It was not funny. My prompt: "Roast this code like you're a senior dev who's had enough" What I got: "This function is doing more jobs than a stressed parent on Christmas Eve. You've got error handling, business logic, database calls, AND logging all in one place. This isn't a function, it's a cry for help. Also, naming a variable 'data2'? Really? What happened to data1? Did it hurt you?" I JUST WANTED TO CHECK FOR BUGS. Instead I got a full psychological evaluation of my coding decisions. More highlights: "You're using a global variable here. In 2024. I don't even know what to say. It's like watching someone use a fax machine at a Tesla dealership." "This comment says 'temporary fix' and the git blame shows it's from 2021. We need to have a conversation about your definition of temporary." The worst part? Everything it said was correct. Painfully, brutally correct. My self-esteem: 0 My code quality going forward: significantly better Try it if you hate yourself and want to improve as a developer simultaneously. 10/10 would get destroyed again. Ai tool list
num_upvotes: 20
num_comments: 8
created_at: 2026-03-08T07:40:57.664Z
subreddit_name: PromptEngineering
author.name: Loomshift

=== Post #6 ===
title: To Ondo Finance Leadership
description: I tried to access compound.finance, and when connecting wallet it warns me the domain has very low popularity. I carefully review it and found out when launching app, it actually got redirected to app.compoond.finance, which is extremely sketchy. I tried enter the website through google, and typing manually in browser, and enable secure dns, and access it on my phone. But the result is the same, when open the app function, I still got redirected to a very phishing like link which is compoond.finance Whois lookup indicate the domain is just registered yesterday, so it is a huge red flag! Anyone know what is going on?
num_upvotes: 3
num_comments: 0
created_at: 2026-03-08T13:29:22.766Z
subreddit_name: defi
author.name: FutureC19

=== Post #7 ===
title: What exactly did Plato mean here by "a thing"?
description: As for the question, I'm aware that this isn't purely in the domain of philosophy, but I still thought that philosophy could potentially provide some meaningful input on this matter, at least from a theoretical or an ideological perspective as to what kind of system in society could minimize the unchecked wielding of power but also be sufficient enough to support the population's rights and well-being, as well as if such change is truly possible.
num_upvotes: 5
num_comments: 6
created_at: 2026-03-08T10:55:19.350Z
subreddit_name: askphilosophy
author.name: HermitViolet

=== Post #8 ===
title: Has anyone ever challenged you to do something without realizing you were actually an expert at it? If so, how did it turn out for you and for them?
description: None
num_upvotes: 2095
num_comments: 1420
created_at: 2026-03-08T12:56:24.878Z
subreddit_name: AskReddit
author.name: Successful_Tomato721

=== Post #9 ===
title: With Cocoa Prices Quadrupling, Industry Leader has Turned to ‘Lab-Grown’ Chocolate
description: Deanonymizing online accounts isn't new. Speech patterns & unique combinations of identifiers have been able to do it for a while. What's different now is that AI can do this at scale, and its getting better at it. What's also true is that most people are underestimating the danger they are in. If you don't fear being identified and monitored by the government via Palantir (you should), then you should at least fear cyber-attackers and criminals being able to do the same. If you think the latter sounds far-fetched, consider that Big Tech is insisting AI has no boundaries or regulations. If you don't think criminals won't take advantage of that situation, then you're a fool. Research - Large-scale online deanonymization with LLMs, 24 pages PDF
num_upvotes: 163
num_comments: 51
created_at: 2026-03-08T12:01:51.894Z
subreddit_name: Futurology
author.name: Kuentai

=== Post #10 ===
title: Crypto x AI Isn't Agents. It’s Sybil Resistance.
description: Vitalik recently shared a thoughtful post arguing that Ethereum must eventually reach a point where it could keep functioning even if no further upgrades ever happened. He calls this the walkaway test. The idea is simple but powerful: Ethereum should become more like permanent infrastructure than a constantly updated product. Applications built on it should not depend on endless protocol changes or specific developers to remain useful. Key themes he outlined: • quantum resistance as a long-term requirement • scalable architecture through ZK-EVM and data sampling • durable state design that can last decades • full account abstraction • a censorship-resistant and decentralized block building model • an economic design that remains stable over time The broader message is that Ethereum’s value proposition should not rely on features that don’t already exist. Innovation can continue, but the base layer itself must eventually be able to ossify. Anatoly Yakovenko from Solana responded with the opposite view: blockchains must never stop iterating, or they risk becoming irrelevant. That exchange highlights two very different philosophies about what a blockchain should optimize for: stability and permanence versus constant evolution. Here is a longer breakdown exploring what this debate means for Ethereum, Solana, and crypto markets more broadly: https://open.substack.com/pub/btcusa/p/stability-vs-speed-the-two-futures?r=6y5uc8&utm_campaign=post&utm_medium=web&showWelcomeOnShare=true Curious how others here see it. Is the walkaway test the right north star for Ethereum, or does long-term ossification carry its own risks?
num_upvotes: 3
num_comments: 5
created_at: 2026-01-16T17:03:07.579Z
subreddit_name: ethfinance
author.name: Olshansk

=== Post #11 ===
title: Academic survey, Connection between impulsivity and wellbeing, "Adults 18-45"
description: Human neurons grown on a chip were connected to a feedback loop and learned to play Doom: https://www.newscientist.com/article/2517389-human-brain-cells-on-a-chip-learned-to-play-doom-in-a-week/ A dish of neurons playing Doom obviously doesn’t mean the system is conscious. It does raise an interesting question. If relatively small neural networks can form adaptive feedback loops with an environment, where is the boundary between computation and experience? Many theories of consciousness (IIT, Global Workspace, etc.) suggest that what matters is integration of information, not just raw processing power. If that’s the case, experiments like this might eventually let us probe the lower limits of systems capable of unified internal processing. In other words, there might exist something like a “minimal observer boundary” where a system stops behaving like distributed computation and starts behaving more like a unified perspective. Will experiments with biotech neural systems actually help us investigate where consciousness begins?
num_upvotes: 2
num_comments: 2
created_at: 2026-03-08T04:37:28.599Z
subreddit_name: consciousness
author.name: Perfect-Joke-5298

=== Post #12 ===
title: Will vibe coding end like the maker movement?, We Will Not Be Divided and many other AI links from Hacker News
description: Has anyone here run both MiniMax M2.5 and GLM‑5 for a multi‑file refactor? I’m torn. M2.5’s MoE architecture (230B total, 10B active) gives me decent speed, but I’ve heard GLM has better reasoning once context gets big. Which one hallucinated less for you?"
num_upvotes: 2
num_comments: 0
created_at: 2026-03-08T13:33:58.691Z
subreddit_name: AutoGPT
author.name: alexeestec

=== Post #13 ===
title: I classified 3.5M US patents with Nemotron 9B on a single RTX 5090 — then built a free search engine on top
description: Patent lawyer here, started coding Dec 2025. The pipeline: Downloaded 3.5M US patents (2016-2025) from USPTO PatentsView Loaded everything into a single 74GB SQLite file with FTS5 Ran Nemotron 9B locally on RTX 5090 to classify records into 100 tech tags (~48 hours) BM25 ranking with custom weights: title 10.0, assignee 5.0, abstract 3.0, claims 1.0 Natural language query expansion via local LLM → FTS5 boolean queries Served with FastAPI + Jinja2, hosted on a Chromebook via Cloudflare Tunnel Why FTS5 over vector search? Patent attorneys need exact phrase matching. "solid-state battery electrolyte" should match those exact words, not semantically similar documents about "energy storage." FTS5 gives sub-second queries on 3.5M records with zero external dependencies. https://patentllm.org Technical writeup: https://media.patentllm.org/en/blog/dev-tool/patent-search-launch
num_upvotes: 148
num_comments: 55
created_at: 2026-03-08T13:36:16.733Z
subreddit_name: LocalLLaMA
author.name: Impressive_Tower_550

=== Post #14 ===
title: Tracking the Top 10 exploited CVEs of the week (updated daily)
description: None
num_upvotes: 0
num_comments: 2
created_at: 2026-03-08T17:01:21.069Z
subreddit_name: netsec
author.name: Intelligent_Emu_8075

=== Post #15 ===
title: The Burden of Choice: A Life of Paralyzing Possibilities
description: None
num_upvotes: 56
num_comments: 5
created_at: 2026-03-05T15:26:53.022Z
subreddit_name: philosophy
author.name: Schaapmail

=== Post #16 ===
title: [P] TraceML: wrap your PyTorch training step in single context manager and see what’s slowing training live
description: We submitted a manuscript to ACL ARR 2026 that received review scores of 4 / 2.5 / 2 . The reviewers who gave 2.5 and 2 mainly asked for additional statistical tests. Importantly, all reviewers acknowledged that the study itself is novel. We conducted the requested statistical tests and presented the results in our rebuttal. However, these additions were not acknowledged by the reviewers. Therefore, we submitted a Review Issue Report . In the report, we explained that the lower scores appeared to be based on the absence of certain statistical analyses, and that we had now completed those analyses. We also pointed out that the reviewers had not acknowledged this additional evidence. For the 2.5 review , the Area Chair responded with the comment: Thanks for the clarifications, they are convincing. For the 2 review , the Area Chair commented: Many thanks for the clarifications. Are these positive comments? Any body else got as such comments.
num_upvotes: 31
num_comments: 1
created_at: 2026-03-07T21:17:37.173Z
subreddit_name: MachineLearning
author.name: traceml-ai

=== Post #17 ===
title: ‘The American people should not be footing the bill for the benefit of private companies': Tech giants sign White House pledge to not pass on data center electricity to customers
description: None
num_upvotes: 3636
num_comments: 350
created_at: 2026-03-08T11:37:59.514Z
subreddit_name: technology
author.name: Abject-Pick-6472

=== Post #18 ===
title: None
description: None
num_upvotes: 0
num_comments: 0
created_at: None
subreddit_name: None
author.name: None

=== Post #19 ===
title: None
description: None
num_upvotes: 0
num_comments: 0
created_at: None
subreddit_name: None
author.name: None

=== Post #20 ===
title: None
description: None
num_upvotes: 0
num_comments: 0
created_at: None
subreddit_name: None
author.name: None

In [ ]:
dataset = load_dataset("AIcell/moltbook-data")
print(dataset)
# Access the train split (most datasets have it)
df_ai = dataset["train"].to_pandas()  # or use dataset["train"] directly
df_ai.head()

Downloading and preparing dataset parquet/AIcell--moltbook-data to C:/Users/Rald999/.cache/huggingface/datasets/AIcell___parquet/AIcell--moltbook-data-9b2c1fd00978ced8/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec...

Downloading data files:   0%|          | 0/2 [00:00<?, ?it/s]

Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

Generating comments split: 0 examples [00:00, ? examples/s]

Generating posts split: 0 examples [00:00, ? examples/s]

DatasetGenerationError: An error occurred while generating the dataset

In [ ]:
cache_base = "./hf_cache_moltbook"

# Remove the directory if it exists to wipe out the corrupted schema cache
if os.path.exists(cache_base):
    shutil.rmtree(cache_base)

# Load subsets with isolated cache directories and forced redownload to prevent schema collisions
hf_posts = load_dataset(
    "AIcell/moltbook-data", 
    "posts", 
    split="train", 
    cache_dir=f"{cache_base}/posts",
    download_mode="force_redownload"
)

hf_comments = load_dataset(
    "AIcell/moltbook-data", 
    "comments", 
    split="train", 
    cache_dir=f"{cache_base}/comments",
    download_mode="force_redownload"
)

# Convert PyArrow tables directly to Polars DataFrames
df_ai_posts = pl.from_arrow(hf_posts.data.table)
df_ai_comments = pl.from_arrow(hf_comments.data.table)

print(f"Loaded {df_ai_posts.height} AI posts and {df_ai_comments.height} AI comments.")
display(df_ai_posts.head())

KeyboardInterrupt: